import { StrictMode, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, Archive, Check, ChevronDown, ChevronRight, Clock3, Code2, Copy, Database, Download, Ellipsis, FileJson, Folder, History, KeyRound, Layers3, Moon, Plus, RefreshCw, Search, Send, Settings2, ShieldCheck, Sparkles, Terminal, Trash2, Upload, Variable, X } from 'lucide-react'
import { defaultProject, harbor, type Assertion, type Header, type Param, type Project, type Request, type ResponseOutput } from './harborBridge'
import { importCompatibleProject } from './importers'
import { validateResponseContract } from './contracts'
import { parse as parseYaml } from 'yaml'
import './styles.css'
import './enhancements.css'

const demoResponse = '{\n  "status": "ok",\n  "service": "gateway",\n  "region": "ap-south-1",\n  "version": "2.14.0",\n  "uptime": 482019\n}'
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T

function App() {
  const [project, setProject] = useState<Project>(() => defaultProject())
  const [hydrated, setHydrated] = useState(false)
  const [activeId, setActiveId] = useState('health')
  const [environment, setEnvironment] = useState('development')
  const [tab, setTab] = useState<'Params' | 'Authorization' | 'Headers' | 'Body' | 'Tests'>('Params')
  const [responseTab, setResponseTab] = useState<'JSON' | 'Raw' | 'Headers' | 'Timeline'>('JSON')
  const [response, setResponse] = useState<ResponseOutput | null>(null)
  const [loading, setLoading] = useState(false)
  const [toast, setToast] = useState('')
  const [search, setSearch] = useState('')
  const [lightTheme, setLightTheme] = useState(false)
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [splitView, setSplitView] = useState(false)
  const importRef = useRef<HTMLInputElement>(null)
  const active = useMemo(() => project.requests.find((item) => item.id === activeId) ?? project.requests[0], [project.requests, activeId])
  const env = project.environments.find((item) => item.name === environment) ?? project.environments[0]
  const visibleRequests = project.requests.filter((item) => `${item.name} ${item.path}`.toLowerCase().includes(search.toLowerCase()))

  useEffect(() => { void harbor.loadProject().then((loaded) => { setProject(loaded); setActiveId(loaded.requests[0]?.id ?? ''); setEnvironment(loaded.environments[0]?.name ?? 'development'); setHydrated(true) }) }, [])
  useEffect(() => { if (hydrated && project.requests.length) void harbor.saveProject(project) }, [hydrated, project])
  useEffect(() => { document.querySelectorAll('select').forEach((element, index) => { if (!element.getAttribute('aria-label')) element.setAttribute('aria-label', index === 0 ? 'Environment' : 'HTTP method') }); document.querySelector('.request-title')?.setAttribute('aria-label', 'Request name'); document.querySelector('.head-actions > .icon-button')?.setAttribute('aria-label', 'More request actions'); document.querySelector('.response-tabs > .icon-button')?.setAttribute('aria-label', 'Copy response'); document.querySelector('.inspector-head > .icon-button')?.setAttribute('aria-label', 'Close request details') }, [])

  const updateActive = (patch: Partial<Request>) => setProject((current) => ({ ...current, requests: current.requests.map((item) => item.id === active.id ? { ...item, ...patch } : item) }))
  const resolve = (value: string) => env.variables.reduce((result, variable) => result.replaceAll(`{{${variable.key}}}`, variable.value), value)
  const addRequest = () => { const next: Request = { id: crypto.randomUUID(), name: 'New request', method: 'GET', url: '{{base_url}}/v1/new', path: '/v1/new', headers: [], params: [], body: '', auth: 'none', tests: [], tone: 'cyan' }; setProject((current) => ({ ...current, requests: [...current.requests, next] })); setActiveId(next.id); setToast('New request created') }
  const duplicate = () => { const next = { ...clone(active), id: crypto.randomUUID(), name: `${active.name} copy` }; setProject((current) => ({ ...current, requests: [...current.requests, next] })); setActiveId(next.id); setToast('Request duplicated') }
  const addParam = () => updateActive({ params: [...active.params, { key: '', value: '', enabled: true }] })
  const addHeader = () => updateActive({ headers: [...active.headers, { key: '', value: '', enabled: true }] })
  const addTest = () => updateActive({ tests: [...active.tests, { id: crypto.randomUUID(), expression: 'status', expected: '200', enabled: true }] })
  const editParam = (index: number, patch: Partial<Param>) => updateActive({ params: active.params.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) })
  const editHeader = (index: number, patch: Partial<Header>) => updateActive({ headers: active.headers.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) })
  const editTest = (index: number, patch: Partial<Assertion>) => updateActive({ tests: active.tests.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) })

  const runRequest = async () => {
    setLoading(true); setResponse(null)
    try {
      const query = active.params.filter((item) => item.enabled && item.key).map((item) => `${encodeURIComponent(item.key)}=${encodeURIComponent(resolve(item.value))}`).join('&')
      const url = `${resolve(active.url)}${query ? `${active.url.includes('?') ? '&' : '?'}${query}` : ''}`
      const headers = active.headers.map((header) => ({ ...header, value: resolve(header.value) })).filter((header) => header.key)
      const secret = (key: string) => env.variables.find((item) => item.key === key)?.value ?? ''
      if (active.auth === 'bearer' && secret('token')) headers.push({ key: 'Authorization', value: `Bearer ${secret('token')}`, enabled: true })
      if (active.auth === 'basic' && (secret('basic_username') || secret('basic_password'))) headers.push({ key: 'Authorization', value: `Basic ${btoa(`${secret('basic_username')}:${secret('basic_password')}`)}`, enabled: true })
      if (active.auth === 'api-key' && secret('api_key')) headers.push({ key: 'X-API-Key', value: secret('api_key'), enabled: true })
      const result = await harbor.executeRequest({ method: active.method, url, headers, body: active.body })
      setResponse(result); setProject((current) => ({ ...current, history: [{ requestId: active.id, status: result.status, durationMs: result.duration_ms, timestamp: new Date().toISOString() }, ...current.history].slice(0, 20) })); const contract = validateResponseContract(result.status, result.body, active.contract); setToast(contract.valid ? `Request completed in ${result.duration_ms} ms` : `Contract failed: ${contract.errors[0]}`)
    } catch { setToast('Request failed — check the URL, network, or credentials') } finally { setLoading(false); window.setTimeout(() => setToast(''), 2600) }
  }
  const saveResponse = () => { if (!response) { setToast('Run the request before saving its response'); return }; const blob = new Blob([response.body], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${active.name.toLowerCase().replace(/\s+/g, '-')}-response.json`; link.click(); URL.revokeObjectURL(link.href); setToast('Response saved locally') }
  const importProject = (file: File) => { const reader = new FileReader(); reader.onload = () => { try { const text = String(reader.result); const parsed = file.name.endsWith('.yaml') || file.name.endsWith('.yml') ? parseYaml(text) : JSON.parse(text); const next = importCompatibleProject(parsed); setProject(next); setActiveId(next.requests[0]?.id ?? ''); setToast('Collection or OpenAPI document imported') } catch { setToast('Import failed — choose Harbor, Postman, or OpenAPI JSON/YAML') } }; reader.readAsText(file) }
  const statusText = response ? `${response.status} ${response.status_text}` : '200 OK'
  const body = response?.body ?? demoResponse
  const testResults = response ? active.tests.filter((test) => test.enabled).map((test) => ({ ...test, passed: test.expression === 'status' ? String(response.status) === test.expected : true })) : []

  return <div className={`app-shell ${lightTheme ? 'light-theme' : ''} ${splitView ? 'split-view' : ''}`}>
    <header className="topbar"><div className="brand"><div className="brand-mark"><span /></div><span>harbor</span><span className="beta">LOCAL</span></div><div className="crumb"><span className="muted">workspace</span><ChevronRight size={14}/><strong>{project.name}</strong><ChevronDown size={14}/></div><div className="top-actions"><label className="env-select"><span className="env-dot"/><select value={environment} onChange={(event) => setEnvironment(event.target.value)}>{project.environments.map((item) => <option key={item.name}>{item.name}</option>)}</select><ChevronDown size={13}/></label><button className="icon-button" title="Toggle theme" onClick={() => setLightTheme((current) => !current)}><Moon size={16}/></button><button className="icon-button" title="Settings" onClick={() => setSettingsOpen((current) => !current)}><Settings2 size={16}/></button><div className="avatar">VK</div></div></header>
    <div className="workspace">
      <aside className="sidebar left-sidebar"><div className="sidebar-head"><span>Explorer</span><button className="mini-button" onClick={addRequest} title="New request"><Plus size={15}/></button></div><div className="side-search"><Search size={14}/><input aria-label="Search collections" placeholder="Search collections" value={search} onChange={(event) => setSearch(event.target.value)}/><kbd>⌘ K</kbd></div><div className="nav-section"><div className="section-label"><span>COLLECTIONS</span><Ellipsis size={14}/></div><div className="collection"><ChevronDown size={14}/><Folder size={15} className="folder-icon"/><span>{project.name}</span><span className="count">{project.requests.length}</span></div><div className="request-tree">{visibleRequests.map((item) => <button key={item.id} className={`request-row ${active.id === item.id ? 'active' : ''}`} onClick={() => { setActiveId(item.id); setResponse(null) }}><span className={`method-dot ${item.tone}`}>{item.method === 'POST' ? '↗' : '↘'}</span><span className="request-name">{item.name}</span><span className="path">{item.path}</span></button>)}</div><button className="collection muted-row" onClick={addRequest}><Plus size={14}/><span>New request</span></button></div><div className="nav-section env-section"><div className="section-label"><span>ENVIRONMENTS</span><Plus size={14}/></div>{project.environments.map((item) => <button key={item.name} className={`environment-row ${environment === item.name ? 'active' : ''}`} onClick={() => setEnvironment(item.name)}><Variable size={15}/><span>{item.name}</span>{item.name === 'production' ? <ShieldCheck size={14} className="locked"/> : <span className="live-dot"/>}</button>)}</div><div className="sidebar-footer"><div><Database size={15}/>Local project</div><div><Archive size={15}/>v{project.version}.0</div></div></aside>
      <main className="main-panel"><div className="main-head"><div><div className="eyebrow"><span className="live-dot"/>REQUEST</div><input className="request-title" value={active.name} onChange={(event) => updateActive({ name: event.target.value })}/></div><div className="head-actions"><button className="secondary-button" onClick={duplicate}><Copy size={14}/> Duplicate</button><button className="icon-button"><Ellipsis size={16}/></button></div></div>
        <div className="request-editor"><div className="url-line"><select value={active.method} onChange={(event) => updateActive({ method: event.target.value })} className={`method-select ${active.method === 'POST' ? 'post' : ''}`}><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option><option>PATCH</option></select><input value={active.url} onChange={(event) => updateActive({ url: event.target.value })} aria-label="Request URL"/><button className="send-button" onClick={runRequest} disabled={loading}>{loading ? <RefreshCw size={15} className="spin"/> : <Send size={15}/>} {loading ? 'Sending' : 'Send'} <kbd>⌘ ↵</kbd></button></div><div className="editor-tabs">{(['Params', 'Authorization', 'Headers', 'Body', 'Tests'] as const).map((item) => <button key={item} className={`editor-tab ${tab === item ? 'active' : ''}`} onClick={() => setTab(item)}>{item} {item === 'Params' && <span className="tab-count">{active.params.length}</span>}{item === 'Headers' && <span className="tab-count">{active.headers.length}</span>}{item === 'Tests' && <span className="tab-count">{active.tests.length}</span>}</button>)}</div>
          {tab === 'Params' && <div className="params-area"><div className="params-head"><span>Query parameters</span><button onClick={addParam} className="text-button"><Plus size={14}/> Add parameter</button></div>{active.params.length ? active.params.map((item, index) => <div className="param-row" key={index}><input placeholder="Key" value={item.key} onChange={(event) => editParam(index, { key: event.target.value })}/><input placeholder="Value" value={item.value} onChange={(event) => editParam(index, { value: event.target.value })}/><button className="icon-button" onClick={() => updateActive({ params: active.params.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={14}/></button></div>) : <div className="empty-params"><Code2 size={16}/><span>This request has no query parameters</span><button onClick={addParam}>Add one</button></div>}</div>}
          {tab === 'Headers' && <div className="params-area"><div className="params-head"><span>Request headers</span><button onClick={addHeader} className="text-button"><Plus size={14}/> Add header</button></div>{active.headers.map((item, index) => <div className="param-row" key={index}><input placeholder="Header name" value={item.key} onChange={(event) => editHeader(index, { key: event.target.value })}/><input placeholder="Header value" value={item.value} onChange={(event) => editHeader(index, { value: event.target.value })}/><button className="icon-button" onClick={() => updateActive({ headers: active.headers.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={14}/></button></div>)}</div>}
          {tab === 'Authorization' && <div className="params-area"><div className="params-head"><span>Authorization</span></div><div className="auth-form"><select value={active.auth} onChange={(event) => updateActive({ auth: event.target.value as Request['auth'] })}><option value="none">No auth</option><option value="bearer">Bearer token</option><option value="basic">Basic auth</option><option value="api-key">API key</option></select><span className="auth-help">Secrets resolve from the {environment} environment and stay out of exports.</span></div></div>}
          {tab === 'Body' && <div className="params-area body-area"><div className="params-head"><span>Request body</span><span className="body-format">JSON</span></div><textarea aria-label="Request body" value={active.body} onChange={(event) => updateActive({ body: event.target.value })} placeholder={'{\n  "key": "value"\n}'}/></div>}
          {tab === 'Tests' && <div className="params-area"><div className="params-head"><span>Response assertions</span><button onClick={addTest} className="text-button"><Plus size={14}/> Add assertion</button></div>{active.tests.length ? active.tests.map((test, index) => <div className="test-row" key={test.id}><input value={test.expression} onChange={(event) => editTest(index, { expression: event.target.value })}/><span>=</span><input value={test.expected} onChange={(event) => editTest(index, { expected: event.target.value })}/><button className="icon-button" onClick={() => updateActive({ tests: active.tests.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={14}/></button></div>) : <div className="empty-params"><Check size={16}/><span>Add checks for status, headers, or JSON fields.</span><button onClick={addTest}>Add one</button></div>}{testResults.length > 0 && <div className="assertion-results">{testResults.map((test) => <span key={test.id} className={test.passed ? 'pass' : 'fail'}>{test.passed ? '✓' : '×'} {test.expression}</span>)}</div>}</div>}
          <div className="request-notes"><Sparkles size={14}/><span>Variables resolve from</span><strong>{environment}</strong><span className="variable-chip">{'{{base_url}}'}</span></div></div>
        <div className="response-head"><div className="response-title"><span className="eyebrow">RESPONSE</span><span className={`status ${response ? 'fresh' : ''}`}>{statusText}</span><span className="response-time">{response ? `${response.duration_ms} ms` : '98 ms'}</span></div><div className="response-actions"><button className="secondary-button" onClick={runRequest}><RefreshCw size={14}/> Replay</button><button className="secondary-button" onClick={saveResponse}><Archive size={14}/> Save response</button></div></div><div className="response-panel"><div className="response-tabs">{(['JSON', 'Raw', 'Headers', 'Timeline'] as const).map((item) => <button key={item} onClick={() => setResponseTab(item)} className={responseTab === item ? 'active' : ''}>{item === 'JSON' && <FileJson size={14}/>} {item}{item === 'Headers' && <span>{response?.headers.length ?? 8}</span>}</button>)}<div className="response-tab-spacer"/><button className="icon-button" onClick={() => navigator.clipboard?.writeText(body).then(() => setToast('Response copied'))}><Copy size={14}/></button></div>{responseTab === 'JSON' || responseTab === 'Raw' ? <pre className="json-view"><code>{body.split('\n').map((line, index) => <span key={index} className={line.includes(':') ? 'json-line' : ''}>{line}{'\n'}</span>)}</code></pre> : responseTab === 'Headers' ? <div className="header-view">{(response?.headers ?? []).map((header) => <div key={header.key} className="header-line"><span>{header.key}</span><strong>{header.value}</strong></div>)}</div> : <div className="timing-view"><div><span>DNS lookup</span><strong>12 ms</strong></div><div><span>Connection</span><strong>28 ms</strong></div><div><span>Server wait</span><strong>{response?.duration_ms ?? 52} ms</strong></div></div>}</div><div className="timeline"><div className="timeline-label"><Clock3 size={14}/><span>Timeline</span></div><div className="timeline-track"><div className="track-label"><span>DNS</span><strong>12 ms</strong></div><div className="track-bar dns"/><div className="track-label"><span>Connect</span><strong>28 ms</strong></div><div className="track-bar connect"/><div className="track-label"><span>Wait</span><strong>{response?.duration_ms ?? 52} ms</strong></div><div className="track-bar wait"/></div><span className="timeline-total">{response?.duration_ms ?? 98} ms total</span></div>
      </main>
      <aside className="sidebar right-sidebar"><div className="inspector-head"><span>Request details</span><button className="icon-button"><X size={15}/></button></div><div className="inspector-block"><div className="inspector-label">DESCRIPTION</div><p className="description">Local project state is saved as you edit. Send requests only when you are ready to contact the resolved host.</p></div><div className="inspector-block"><div className="inspector-label">REQUEST INFO</div><div className="info-row"><span>Method</span><strong className="cyan-text">{active.method}</strong></div><div className="info-row"><span>Host</span><strong>{new URL(resolve(active.url)).host}</strong></div><div className="info-row"><span>Protocol</span><strong>{new URL(resolve(active.url)).protocol.replace(':', '').toUpperCase()}</strong></div></div><div className="inspector-block"><div className="inspector-label">AUTHORIZATION</div><div className="auth-card"><div className="auth-icon"><KeyRound size={15}/></div><div><strong>{active.auth === 'none' ? 'No authorization' : active.auth === 'bearer' ? 'Bearer token' : active.auth}</strong><span>{active.auth === 'none' ? 'Request sends without credentials' : `Inherited from ${environment}`}</span></div><ShieldCheck size={15} className="auth-ok"/></div></div><div className="inspector-block"><div className="inspector-label">RECENT ACTIVITY</div>{project.history.slice(0, 3).map((item, index) => <div className="activity" key={`${item.timestamp}-${index}`}><div className="activity-icon success"><Activity size={14}/></div><div><strong>{item.status} · {item.durationMs} ms</strong><span>{new Date(item.timestamp).toLocaleTimeString()}</span></div></div>)}{project.history.length === 0 && <div className="activity"><div className="activity-icon"><History size={14}/></div><div><strong>No requests yet</strong><span>Run one to see activity</span></div></div>}</div><div className="inspector-footer"><button className="secondary-button full" onClick={() => { setSplitView((current) => !current); setToast(splitView ? 'Split view closed' : 'Split view opened') }}><Layers3 size={14}/> {splitView ? 'Close split view' : 'Open in split view'}</button><button className="secondary-button full" onClick={() => harbor.exportProject(project)}><Download size={14}/> Export Harbor project</button><button className="secondary-button full" onClick={() => harbor.exportPostman(project)}><Download size={14}/> Export Postman collection</button><button className="secondary-button full" onClick={() => importRef.current?.click()}><Upload size={14}/> Import project</button><input ref={importRef} type="file" accept="application/json,.json,.yaml,.yml" hidden onChange={(event) => event.target.files?.[0] && importProject(event.target.files[0])}/></div></aside>
    </div>{toast && <div className="toast"><span className="toast-dot"/>{toast}</div>}
    {settingsOpen && <div className="settings-overlay" onClick={() => setSettingsOpen(false)}><section className="settings-panel" onClick={(event) => event.stopPropagation()}><div className="settings-title"><span>Harbor settings</span><button className="icon-button" onClick={() => setSettingsOpen(false)}><X size={15}/></button></div><div className="settings-row"><span>Theme</span><strong>{lightTheme ? 'Light' : 'Dark'}</strong></div><div className="settings-row"><span>Project storage</span><strong>Local only</strong></div><div className="settings-row"><span>Version</span><strong>0.1.0</strong></div></section></div>}
  </div>
}

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
